version: '3'
services:
  web:
    build:
      #context: .
      #dockerfile: .docker/web/Dockerfile
      context: .docker/web
    image: magento2_nginx_web
    ports:
      - 80:80
    depends_on:
      - fpm
    volumes:
      - ./www:/var/www/mage2.ph
    networks:
      - magento2-nginx-network
  fpm:
    build:
      context: .docker/fpm
    image: magento2_nginx_fpm
    volumes:
      - ./www:/var/www/mage2.ph
    networks:
      - magento2-nginx-network
    links:
      - db
      - rabbitmq
      - redis-session
      - redis-cache
      - elasticsearch
  cli:
    build:
      context: .docker/cli
    image: magento2_nginx_cli
    tty: true
    volumes:
      - ./www:/var/www/mage2.ph
    networks:
      - magento2-nginx-network
    links:
      - db
      - rabbitmq
      - redis-session
      - redis-cache
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root.1234
      MYSQL_DATABASE: mage2_db
      MYSQL_USER: mage2_db_admin
      MYSQL_PASSWORD: AdminDb.1234
    volumes:
      - mage2_db:/var/lib/mysql
    networks:
      - magento2-nginx-network
  rabbitmq:
    image: rabbitmq:3.7.8-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: mage2_rmq_user
      RABBITMQ_DEFAULT_PASS: AdminRmq.1234
    networks:
      - magento2-nginx-network
  redis-cache:
    image: redis:5.0.3-alpine
    command: redis-server --requirepass Redis.1234
    networks:
      - magento2-nginx-network
    volumes:
      - redis-cache-data:/data
  redis-session:
    image: redis:5.0.3-alpine
    command: redis-server --requirepass Redis.1234
    networks:
      - magento2-nginx-network
    volumes:
      - redis-session-data:/data
  elasticsearch:
    image: elasticsearch:5.6.14-alpine
    networks:
      - magento2-nginx-network
    volumes:
      - es-data:/usr/share/elasticsearch/data
networks:
  magento2-nginx-network:
    # driver: bridge

volumes:
  mage2_db:
  redis-cache-data:
  redis-session-data:
  es-data:
